# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

# Dev Keys
# TWITTER_KEY: dWlWQP6MKd6yliJQvB4FA
# TWITTER_SECRET: ABXEZ4IGJKjzhIZD8Mv1MurxI49tDz4kF9IAuckUY
# LINKEDIN_KEY: tf1hj3b0f8lt
# LINKEDIN_SECRET: ml71gD8icj9pF1Nv
# LINKEDIN_API_KEY: cd1161d2-8f50-4a84-a8ab-8ea78f21313e
# LINKEDIN_API_SECRET: e2772b4a-06bd-474f-9615-22222ea7c1e1
# FACEBOOK_KEY: 158379167673562
# FACEBOOK_SECRET: f3216cadbe9919440663871020508e7c

TWITTER_KEY: arvJ50DtP168ViDsbXGNg
TWITTER_SECRET: oT25i7z0EmiVJuRy2vJEbljWemJlAkXX0I1VURUWBVY
LINKEDIN_KEY: udc5j8ffzpzv
LINKEDIN_SECRET: pG8vIPSOTPzzzqlr
LINKEDIN_API_KEY: 29003f58-c010-4116-a5a8-bc95c4fa4374
LINKEDIN_API_SECRET: 2a56153f-3437-4c80-b5fc-cf8d63086156
FACEBOOK_KEY: 543925345644816
FACEBOOK_SECRET: b5e1202bf99ff334a2f155c48d127713
# BALANCED_KEY: 7baa4a60aed811e29c91026ba7c1aba6
BALANCED_KEY: nil
AWS_KEY: AKIAIBUPOW2RUYWNZRVQ
AWS_SECRET: 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