# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

TWITTER_KEY: dWlWQP6MKd6yliJQvB4FA
TWITTER_SECRET: ABXEZ4IGJKjzhIZD8Mv1MurxI49tDz4kF9IAuckUY
LINKEDIN_KEY: tf1hj3b0f8lt
LINKEDIN_SECRET: ml71gD8icj9pF1Nv
LINKEDIN_API_KEY: cd1161d2-8f50-4a84-a8ab-8ea78f21313e
LINKEDIN_API_SECRET: e2772b4a-06bd-474f-9615-22222ea7c1e1
FACEBOOK_KEY: 158379167673562
FACEBOOK_SECRET: f3216cadbe9919440663871020508e7c
# BALANCED_KEY: 7baa4a60aed811e29c91026ba7c1aba6
BALANCED_KEY: nil
AWS_KEY: AKIAIBUPOW2RUYWNZRVQ
AWS_SECRET: 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